apiVersion: v1
kind: Service
metadata:
  name: permia-backend
  labels:
    app: permia-backend
spec:
  type: ClusterIP
  selector:
    app: permia-backend
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8000
  sessionAffinity: None
